import java.util.ArrayList;
import java.util.Random;
import java.util.Scanner;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        Scanner input = new Scanner(System.in);
       /* System.out.println(new App().getGreeting());
        System.out.println("Enter the number of rolls: ");
        int n = input.nextInt();

        int [] nums = roll(n);
        for (int i = 0; i < n; i++) {
            System.out.println(nums[i]);
        }

        int [] num= {1,5,2,3};
        containsDuplicates(num);



        int [] num= {1,5,2,3};
        System.out.println(averageOfArray(num));

        */

        int[][] weeklyMonthTemperatures = {
                {66, 64, 58, 65, 71, 57, 60},
                {57, 65, 65, 70, 72, 65, 51},
                {55, 54, 60, 53, 59, 57, 61},
                {65, 56, 55, 52, 55, 62, 57}
        };
        int [] arr = new int[weeklyMonthTemperatures[0].length];
        arr = avgOfArraysOfArrays(weeklyMonthTemperatures);
        System.out.println("*************************************");
        for (int i = 0; i < arr.length; i++) {
            System.out.print(arr[i] + " ");
        }
    }

    public static int[] roll(int n){
        int [] num= new int[n];
        Random random = new Random();
        int randnum=0;
        for (int i = 0; i < n; i++) {
            randnum = random.nextInt(6)+1;
            num[i]= randnum;
        }
        return num;
    }


    public static void containsDuplicates(int[] nums){
        boolean flagg =false;
        for (int i = 0; i < nums.length; i++) {
            for (int j = i+1; j < nums.length ; j++) {
                if (nums[i] == nums[j]){
                    flagg= true;
                    break;
                }
            }
        }
        if (flagg)
            System.out.println("The array contains duplicate values");
        else
            System.out.println("The array does not contain duplicate values");

    }

    public static double averageOfArray(int[] num){
        double avg=0;
        int sum=0;
        for (int i = 0; i < num.length; i++) {
            sum+= num[i];
        }
        System.out.println(sum);
        avg = sum /(double)num.length;
        return avg;

    }

    public static int[] avgOfArraysOfArrays(int [][] num){
        int[] arr = new int[num[0].length];
        ArrayList<Double> avgs = new ArrayList<Double>();
        double sum=0;
        double avg = 0;
        for (int i = 0; i < num.length; i++) {
            for (int j = 0; j < num[i].length; j++) {
                sum+= num[i][j];
            }
            avg = sum /(double) num[i].length;
            avgs.add(avg);
            sum=0;
        }
        int inum=0;
        double min= avgs.get(0);
        for (int i = 0; i < avgs.size(); i++) {
            if (min > avgs.get(i)){
                min = avgs.get(i);
                inum= i;
            }
            System.out.print(avgs.get(i)+" , ");


        }
        System.out.println();
        System.out.println("*******************************************");
        System.out.println("min: "+min);
        return num[inum];

    }

}
