import java.util.Scanner;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {

    public static void main(String[] args) {
        Scanner input = new Scanner(System.in);
        String name="", author="", body="";
        double price=0.0 ;
        int numOfStars=0;




            System.out.println("Enter the Resturant's name, and price:  ");
            name = input.next();
            price = input.nextDouble();
            Resturant res = new Resturant(name, price);
        for (int i = 0; i < 3; i++) {
            System.out.println("Please review the resturant, you should write your opinion, your name and rating the resturant by enter a number between [1-5]:  ");
            System.out.println("Enter your name: ");
            author = input.next();
            System.out.println("Enter your opinion: ");
            body = input.next();
            System.out.println("Rate the resturant: [1-5]");
            numOfStars = input.nextInt();
            while (numOfStars < 0 || numOfStars > 5) {
                System.out.println("Please enter the number of stars again: [1 - 5]");
                numOfStars = input.nextInt();
            }

            Review rev = new Review(body, numOfStars, author);
            res.addReview(rev);
            System.out.println(res.toString());
        }
        System.out.println();

    }
}
