import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Random;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        /*int dogCount=1;
        System.out.println("I own "+ dogCount+" "+pluralize("dog", dogCount)+".");
        int catCount = 2;
        System.out.println("I own " + catCount + " " + pluralize("cat", catCount) + ".");

        int turtleCount = 0;
        System.out.println("I own " + turtleCount + " " + pluralize("turtle", turtleCount) + ".");
*/
        flipNHeads(4);


       // clock();
    }



    public static String pluralize(String name, int num){
        String word="";
        if (num ==0 || num >1){
            word=name+"s";
        }else {
            word = name;
        }
        return  word;
    }

    public static void flipNHeads (int num){
        Random random = new Random();
        double randomNumber= random.nextDouble();
        int count=0,  countH=0;
        while (countH < num){
            if (randomNumber <0.5 ) {
                System.out.println("tails");
                countH=0;
            }
            else {
                System.out.println("heads");
                countH++;
            }
            randomNumber= random.nextDouble();
            count++;
        }

        System.out.println("It took "+ count +" flips to flip "+ num +" heads in a row.");
    }

    public static void clock () {
        LocalDateTime previousTime = LocalDateTime.now();



        int count=0;




        while (true) {

            LocalDateTime now = LocalDateTime.now();
            now = LocalDateTime.now();
            try {
                // Sleep for one second (1000 milliseconds)
                Thread.sleep(1000);

            } catch (InterruptedException e) {
                // Handle the exception if necessary
                e.printStackTrace();
            }

            System.out.println(now.format(DateTimeFormatter.ofPattern("HH:mm:ss")));
            count++;
        }



    }


}

