import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {

    public static <Stirng> String tally(List list){
        String name="";
        return name;
    }

    public static void main(String[] args) {
       /* int min=0, max=0;
        HashSet<Integer> temp = new HashSet<Integer>();
        ArrayList<Integer> tempNotSeen = new ArrayList<Integer>();

        // Daily average temperatures for Seattle, October 1-28 2017
        int[][] weeklyMonthTemperatures = {
                {66, 64, 58, 65, 71, 57, 60},
                {57, 65, 65, 70, 72, 65, 51},
                {55, 54, 60, 53, 59, 57, 61},
                {65, 56, 55, 52, 55, 62, 57}
        };
        min=weeklyMonthTemperatures[0][0];
        max=weeklyMonthTemperatures[0][0];
        for (int i = 0; i < weeklyMonthTemperatures.length; i++) {
            for (int j = 0; j < weeklyMonthTemperatures[0].length; j++) {
                if(min > weeklyMonthTemperatures[i][j]){
                    min = weeklyMonthTemperatures[i][j];
                }
                if(max < weeklyMonthTemperatures[i][j]){
                    max=weeklyMonthTemperatures[i][j];
                }

                temp.add(weeklyMonthTemperatures[i][j]);
            }
        }
        System.out.println();
        System.out.println("High: "+ max);
        System.out.println("Low: "+ min);
        System.out.println();
        System.out.println(temp);
        System.out.println();
        for (int i = min; i < max; i++) {
            if(!temp.contains(i)){
                tempNotSeen.add(i);
            }
        }

        for (int i = 0; i < tempNotSeen.size(); i++) {
            System.out.println("Never saw temperature: "+ tempNotSeen.get(i));
        }*/


        // within your main method...
        List<String> votes = new ArrayList<>();
        votes.add("Bush");
        votes.add("Bush");
        votes.add("Bush");
        votes.add("Shrub");
        votes.add("Hedge");
        votes.add("Shrub");
        votes.add("Bush");
        votes.add("Hedge");
        votes.add("Bush");

        String winner = tally(votes);
        System.out.println(winner + " received the most votes!");
    }
}
